### PR TITLE
Add phone number validation

### LINKED ISSUE #155: Add phone number validation
When adding a new household, a phone number is requested. Currently, this field accepts any number of characters. We should add a validation to ensure users enter at least 7 digits into the field.

### PR DESCRIPTION
**Pull request by owais-vd**
close #155

### CODE REVIEW

**Review by ukanga — COMMENTED** [review]
Looks good. I think we may need to hold of on merging this until we get sign off from the client that we should validate this number for minimum/maximum length.

**Comment by owais-vd** [comment]
> Looks good. I think we may need to hold of on merging this until we get sign off from the client that we should validate this number for minimum/maximum length.

sure

**Comment by owais-vd** [comment]
are we going to have this PR or we will still wait? cc: @ukanga @bkimondiu

**Comment by bkimondiu** [comment]
@owais-vd We should wait. I will send let you know what the client says about this one.

**Comment by bkimondiu** [comment]
@owais-vd @ukanga The client was not keen on this validation. It's not a required field and can be left empty. We can disregard adding this validation since they won't be using this phone number data.

**Comment by ukanga** [comment]
Noted.

**Pull request closed without merging**
